"""Blocking (design.md section 5.2).

Blocking is not an optimization.  Comparing every pair is ``n(n-1)/2``: a
million records is 500 billion comparisons, which is 5.8 days at a microsecond
each.  Blocking is the only way this runs at all.

Three design notes from the document, all enforced here:

* **Multiple rules, unioned.**  Any single rule misses pairs; overlapping rules
  recover most of them.
* **Measure recall loss.**  Blocking that misses true pairs caps recall no
  matter how good the scorer is -- see :func:`measure_recall`.
* **Watch for blocks that explode.**  Blocking on ``email_domain`` alone puts
  every ``gmail.com`` address in one block, so every rule conjoins something
  selective and :class:`BlockingStats` reports any block that still blew up.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from itertools import combinations
from typing import Callable, Iterable, Sequence

from lep.core.types import Record
from lep.identity.normalize import normalize_record


@dataclass(frozen=True)
class BlockingRule:
    """A rule generating a blocking key from a record.

    ``sql`` is the equivalent predicate for a Splink/DuckDB or Postgres run;
    the Python ``key`` is what the in-process implementation uses.  Keeping
    both in one place stops the two paths drifting apart.
    """

    name: str
    key: Callable[[Record], str | None]
    sql: str = ""


def _k(*parts: object) -> str | None:
    values = [str(p) for p in parts if p not in (None, "", False)]
    if len(values) != len(parts):
        return None
    return "|".join(values)


#: The starting set from section 5.2.  Every rule pairs something broad with
#: something selective.
BLOCKING_RULES: tuple[BlockingRule, ...] = (
    BlockingRule(
        "domain_and_surname",
        lambda r: _k("dom+ln", r.get("email_domain"), r.get("last_name_dm")),
        "l.email_domain = r.email_domain AND l.last_name_dm = r.last_name_dm",
    ),
    BlockingRule(
        "company_and_first_initial",
        lambda r: _k("co+fi", r.get("normalized_company"), r.get("first_initial")),
        "l.normalized_company = r.normalized_company AND l.first_initial = r.first_initial",
    ),
    BlockingRule(
        "phone",
        lambda r: _k("phone", r.get("phone_e164")),
        "l.phone_e164 = r.phone_e164",
    ),
    BlockingRule(
        "full_name_phonetic",
        lambda r: _k("fn+ln", r.get("first_name_dm"), r.get("last_name_dm")),
        "l.last_name_dm = r.last_name_dm AND l.first_name_dm = r.first_name_dm",
    ),
    BlockingRule(
        "email_local_part",
        lambda r: _k(
            "local", (r.get("email") or "").split("@")[0] if r.get("email") else None
        ),
        "split_part(l.email,'@',1) = split_part(r.email,'@',1)",
    ),
)


@dataclass
class BlockingStats:
    """What blocking cost and what it lost."""

    records: int = 0
    pairs_generated: int = 0
    pairs_all: int = 0
    blocks: int = 0
    oversized_blocks: list[tuple[str, int]] = field(default_factory=list)
    skipped_pairs: int = 0
    per_rule: dict[str, int] = field(default_factory=dict)
    recall: float | None = None
    missed_pairs: list[tuple[str, str]] = field(default_factory=list)

    @property
    def reduction_ratio(self) -> float:
        """Fraction of all possible pairs that blocking removed."""
        if self.pairs_all == 0:
            return 0.0
        return 1.0 - self.pairs_generated / self.pairs_all

    def summary(self) -> str:
        parts = [
            f"{self.records:,} records",
            f"{self.pairs_generated:,} candidate pairs of {self.pairs_all:,} possible",
            f"reduction {self.reduction_ratio:.6f}",
        ]
        if self.recall is not None:
            parts.append(f"recall {self.recall:.4f}")
        if self.oversized_blocks:
            worst = ", ".join(f"{k} ({n:,})" for k, n in self.oversized_blocks[:3])
            parts.append(f"oversized blocks skipped: {worst}")
        return "; ".join(parts)


def blocking_keys(record: Record, rules: Iterable[BlockingRule] = BLOCKING_RULES) -> list[str]:
    return [key for rule in rules if (key := rule.key(record))]


def candidate_pairs(
    records: Sequence[Record],
    rules: Iterable[BlockingRule] = BLOCKING_RULES,
    *,
    max_block_size: int = 1_000,
    stats: BlockingStats | None = None,
) -> set[tuple[str, str]]:
    """Union of pairs generated by every rule.

    A block larger than ``max_block_size`` is skipped and reported rather than
    silently generating ``n^2`` pairs inside it: an exploded block is a bug in
    the rule, and quietly grinding through it is how a matching run turns into
    an outage.
    """
    rules = list(rules)
    index: dict[str, dict[str, list[str]]] = {r.name: defaultdict(list) for r in rules}

    for record in records:
        if not record.normalized:
            # Blocking keys are derived keys.  Normalizing here is idempotent
            # and stops an un-normalized corpus silently producing no pairs.
            normalize_record(record)
        for rule in rules:
            key = rule.key(record)
            if key:
                index[rule.name][key].append(record.key)

    pairs: set[tuple[str, str]] = set()
    report = stats if stats is not None else BlockingStats()
    report.records = len(records)
    report.pairs_all = len(records) * (len(records) - 1) // 2

    for rule in rules:
        rule_pairs = 0
        for key, members in index[rule.name].items():
            report.blocks += 1
            if len(members) > max_block_size:
                report.oversized_blocks.append((f"{rule.name}:{key}", len(members)))
                report.skipped_pairs += len(members) * (len(members) - 1) // 2
                continue
            for a, b in combinations(sorted(set(members)), 2):
                pairs.add((a, b))
                rule_pairs += 1
        report.per_rule[rule.name] = rule_pairs

    report.pairs_generated = len(pairs)
    return pairs


def measure_recall(
    records: Sequence[Record],
    true_pairs: Iterable[tuple[str, str]],
    rules: Iterable[BlockingRule] = BLOCKING_RULES,
    *,
    max_block_size: int = 1_000,
) -> BlockingStats:
    """What fraction of known matches survive blocking?

    This number is a ceiling on the recall of the whole pipeline: a true pair
    that blocking never generates cannot be scored, reviewed, or merged, no
    matter how good the model is.  Run it against the labelled set before
    tuning anything downstream.
    """
    stats = BlockingStats()
    pairs = candidate_pairs(records, rules, max_block_size=max_block_size, stats=stats)
    wanted = {tuple(sorted(p)) for p in true_pairs}
    if not wanted:
        stats.recall = None
        return stats
    found = {p for p in wanted if p in pairs}
    stats.recall = len(found) / len(wanted)
    stats.missed_pairs = sorted(wanted - found)
    return stats


def rule_contribution(
    records: Sequence[Record],
    true_pairs: Iterable[tuple[str, str]],
    rules: Sequence[BlockingRule] = BLOCKING_RULES,
) -> dict[str, float]:
    """Marginal recall of each rule: what would be lost by dropping it.

    Rules with zero marginal contribution are pure cost -- they generate pairs
    the other rules already cover.
    """
    baseline = measure_recall(records, true_pairs, rules).recall or 0.0
    out: dict[str, float] = {}
    for rule in rules:
        without = [r for r in rules if r.name != rule.name]
        recall = measure_recall(records, true_pairs, without).recall or 0.0
        out[rule.name] = round(baseline - recall, 6)
    return out
